# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-26 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social', '0007_auto_20170712_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, unique=True)),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('entry_date', models.DateTimeField(null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=6)),
                ('job_title', models.CharField(max_length=100, null=True, unique=True)),
                ('bio', tinymce.models.HTMLField(max_length=60000, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('image', models.ImageField(max_length=200, upload_to='team/')),
                ('order', models.CharField(max_length=100, null=True)),
                ('social', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social.Social')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, unique=True)),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('entry_date', models.DateTimeField(null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=6)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='teams',
            field=models.ManyToManyField(blank=True, to='profiles.Team'),
        ),
    ]
