# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-22 13:28
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='summary',
            field=tinymce.models.HTMLField(blank=True, max_length=60000, null=True),
        ),
    ]
