# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social', '0002_auto_20170526_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, unique=True)),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
                ('job_title', models.CharField(max_length=100, null=True, unique=True)),
                ('bio', tinymce.models.HTMLField(max_length=60000, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('image', models.ImageField(max_length=200, upload_to='team/')),
                ('order', models.CharField(max_length=100, null=True)),
                ('social', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social.Social')),
                ('teams', models.ManyToManyField(blank=True, to='team.Team')),
            ],
        ),
    ]
