# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='team',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='entry_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='expiration_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='entry_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='expiration_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
