# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('display_title', models.CharField(blank=True, max_length=100)),
                ('background_image', models.ImageField(blank=True, max_length=200, upload_to='backgrounds/')),
                ('background_color', models.CharField(default='f3f3f3', max_length=6)),
                ('order', models.CharField(default='Z', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=2000)),
                ('new_tab', models.BooleanField(default=False)),
                ('order', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NavigationMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('display_title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=100)),
                ('link_url', models.CharField(blank=True, max_length=2000)),
                ('link_text', models.CharField(blank=True, max_length=100)),
                ('background_image', models.ImageField(max_length=200, upload_to='backgrounds/')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.NavigationMenu')),
                ('social', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social.Social')),
            ],
        ),
        migrations.CreateModel(
            name='SectionDefault',
            fields=[
                ('content_ptr', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Content')),
                ('content', tinymce.models.HTMLField(blank=True, max_length=60000)),
                ('image', models.ImageField(blank=True, max_length=200, upload_to='content/')),
            ],
            bases=('pages.content',),
        ),
        migrations.CreateModel(
            name='SectionThreeColumn',
            fields=[
                ('content_ptr', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Content')),
                ('title_left', models.CharField(blank=True, max_length=100)),
                ('content_left', tinymce.models.HTMLField(blank=True, max_length=60000)),
                ('image_left', models.ImageField(blank=True, max_length=200, upload_to='content/')),
                ('title_center', models.CharField(blank=True, max_length=100)),
                ('content_center', tinymce.models.HTMLField(blank=True, max_length=60000)),
                ('image_center', models.ImageField(blank=True, max_length=200, upload_to='content/')),
                ('title_right', models.CharField(blank=True, max_length=100)),
                ('content_right', tinymce.models.HTMLField(blank=True, max_length=60000)),
                ('image_right', models.ImageField(blank=True, max_length=200, upload_to='content/')),
                ('center_text', models.BooleanField(default=False)),
            ],
            bases=('pages.content',),
        ),
        migrations.CreateModel(
            name='SectionTwoColumn',
            fields=[
                ('content_ptr', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Content')),
                ('title_left', models.CharField(blank=True, max_length=100)),
                ('content_left', tinymce.models.HTMLField(blank=True, max_length=60000)),
                ('image_left', models.ImageField(blank=True, max_length=200, upload_to='content/')),
                ('title_right', models.CharField(blank=True, max_length=100)),
                ('content_right', tinymce.models.HTMLField(blank=True, max_length=60000)),
                ('image_right', models.ImageField(blank=True, max_length=200, upload_to='content/')),
                ('center_text', models.BooleanField(default=False)),
            ],
            bases=('pages.content',),
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.NavigationMenu'),
        ),
        migrations.AddField(
            model_name='content',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Page'),
        ),
    ]
