# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-14 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('social', '0007_auto_20170712_1334'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, unique=True)),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('entry_date', models.DateTimeField(null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=6)),
                ('display_title', models.CharField(blank=True, max_length=100, null=True)),
                ('background_image', models.ImageField(blank=True, max_length=200, null=True, upload_to='backgrounds/')),
                ('background_color', models.CharField(blank=True, max_length=6, null=True)),
                ('order', models.CharField(max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, unique=True)),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('entry_date', models.DateTimeField(null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=6)),
                ('display_title', models.CharField(max_length=100, null=True)),
                ('url', models.CharField(max_length=2000, null=True)),
                ('new_tab', models.BooleanField(default=False)),
                ('order', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Navigation - Items',
            },
        ),
        migrations.CreateModel(
            name='NavigationMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, unique=True)),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('entry_date', models.DateTimeField(null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=6)),
            ],
            options={
                'verbose_name_plural': 'Navigation - Menus',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, unique=True)),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('entry_date', models.DateTimeField(null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=6)),
                ('display_title', models.CharField(max_length=100, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('link_url', models.CharField(blank=True, max_length=2000, null=True)),
                ('link_text', models.CharField(blank=True, max_length=100, null=True)),
                ('background_image', models.ImageField(max_length=200, upload_to='backgrounds/')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.NavigationMenu')),
                ('social', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social.Social')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SectionDefault',
            fields=[
                ('content_ptr', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Content')),
                ('content', tinymce.models.HTMLField(max_length=60000, null=True)),
                ('image', models.ImageField(blank=True, max_length=200, null=True, upload_to='content/')),
            ],
            options={
                'verbose_name_plural': 'Sections - Default Template',
            },
            bases=('pages.content',),
        ),
        migrations.CreateModel(
            name='SectionSeries',
            fields=[
                ('content_ptr', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Content')),
                ('series_type', models.CharField(choices=[('weekend', 'Weekend'), ('college', 'College')], default='weekend', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Sections - Series Template',
            },
            bases=('pages.content',),
        ),
        migrations.CreateModel(
            name='SectionTeam',
            fields=[
                ('content_ptr', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Content')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Team')),
            ],
            options={
                'verbose_name_plural': 'Sections - Team Template',
            },
            bases=('pages.content',),
        ),
        migrations.CreateModel(
            name='SectionThreeColumn',
            fields=[
                ('content_ptr', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Content')),
                ('title_left', models.CharField(blank=True, max_length=100, null=True)),
                ('content_left', tinymce.models.HTMLField(blank=True, max_length=60000, null=True)),
                ('image_left', models.ImageField(blank=True, max_length=200, null=True, upload_to='content/')),
                ('title_center', models.CharField(blank=True, max_length=100, null=True)),
                ('content_center', tinymce.models.HTMLField(blank=True, max_length=60000, null=True)),
                ('image_center', models.ImageField(blank=True, max_length=200, null=True, upload_to='content/')),
                ('title_right', models.CharField(blank=True, max_length=100, null=True)),
                ('content_right', tinymce.models.HTMLField(blank=True, max_length=60000, null=True)),
                ('image_right', models.ImageField(blank=True, max_length=200, null=True, upload_to='content/')),
                ('center_text', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Sections - Three Column Template',
            },
            bases=('pages.content',),
        ),
        migrations.CreateModel(
            name='SectionTwoColumn',
            fields=[
                ('content_ptr', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Content')),
                ('title_left', models.CharField(blank=True, max_length=100, null=True)),
                ('content_left', tinymce.models.HTMLField(blank=True, max_length=60000, null=True)),
                ('image_left', models.ImageField(blank=True, max_length=200, null=True, upload_to='content/')),
                ('title_right', models.CharField(blank=True, max_length=100, null=True)),
                ('content_right', tinymce.models.HTMLField(blank=True, max_length=60000, null=True)),
                ('image_right', models.ImageField(blank=True, max_length=200, null=True, upload_to='content/')),
                ('center_text', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Sections - Two Column Template',
            },
            bases=('pages.content',),
        ),
        migrations.CreateModel(
            name='SectionVideo',
            fields=[
                ('content_ptr', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Content')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Video')),
            ],
            options={
                'verbose_name_plural': 'Sections - Single Video Template',
            },
            bases=('pages.content',),
        ),
        migrations.CreateModel(
            name='SectionVideoGroup',
            fields=[
                ('content_ptr', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Content')),
                ('video_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.VideoGroup')),
            ],
            options={
                'verbose_name_plural': 'Sections - Video Group Template',
            },
            bases=('pages.content',),
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.NavigationMenu'),
        ),
        migrations.AddField(
            model_name='content',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Page'),
        ),
    ]
