# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-05 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_auto_20170712_1334'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionEvents',
            fields=[
                ('content_ptr', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Content')),
                ('facebook_page_id', models.CharField(max_length=25, null=True)),
                ('social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.Social')),
            ],
            options={
                'abstract': False,
            },
            bases=('pages.content',),
        ),
    ]
