# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='background_image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='backgrounds/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='display_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='link_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='link_url',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sectiondefault',
            name='content',
            field=tinymce.models.HTMLField(blank=True, max_length=60000, null=True),
        ),
        migrations.AlterField(
            model_name='sectiondefault',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='content/'),
        ),
        migrations.AlterField(
            model_name='sectionthreecolumn',
            name='content_center',
            field=tinymce.models.HTMLField(blank=True, max_length=60000, null=True),
        ),
        migrations.AlterField(
            model_name='sectionthreecolumn',
            name='content_left',
            field=tinymce.models.HTMLField(blank=True, max_length=60000, null=True),
        ),
        migrations.AlterField(
            model_name='sectionthreecolumn',
            name='content_right',
            field=tinymce.models.HTMLField(blank=True, max_length=60000, null=True),
        ),
        migrations.AlterField(
            model_name='sectionthreecolumn',
            name='image_center',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='content/'),
        ),
        migrations.AlterField(
            model_name='sectionthreecolumn',
            name='image_left',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='content/'),
        ),
        migrations.AlterField(
            model_name='sectionthreecolumn',
            name='image_right',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='content/'),
        ),
        migrations.AlterField(
            model_name='sectionthreecolumn',
            name='title_center',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sectionthreecolumn',
            name='title_left',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sectionthreecolumn',
            name='title_right',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sectiontwocolumn',
            name='content_left',
            field=tinymce.models.HTMLField(blank=True, max_length=60000, null=True),
        ),
        migrations.AlterField(
            model_name='sectiontwocolumn',
            name='content_right',
            field=tinymce.models.HTMLField(blank=True, max_length=60000, null=True),
        ),
        migrations.AlterField(
            model_name='sectiontwocolumn',
            name='image_left',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='content/'),
        ),
        migrations.AlterField(
            model_name='sectiontwocolumn',
            name='image_right',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='content/'),
        ),
        migrations.AlterField(
            model_name='sectiontwocolumn',
            name='title_left',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sectiontwocolumn',
            name='title_right',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
