# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20170516_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='navigation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.NavigationMenu'),
        ),
    ]
