# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-07 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_sectionevents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, unique=True)),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('entry_date', models.DateTimeField(null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=6)),
                ('display_title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', tinymce.models.HTMLField(max_length=60000, null=True)),
                ('url', models.CharField(max_length=2000, null=True)),
                ('url_text', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(max_length=200, null=True, upload_to='previews/')),
                ('order', models.CharField(max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PreviewGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, unique=True)),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('entry_date', models.DateTimeField(null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=6)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SectionPreview',
            fields=[
                ('content_ptr', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Content')),
                ('preview_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Preview')),
            ],
            options={
                'verbose_name_plural': 'Sections - Previews Template',
            },
            bases=('pages.content',),
        ),
        migrations.AlterModelOptions(
            name='sectionevents',
            options={'verbose_name_plural': 'Sections - Events Template'},
        ),
        migrations.AddField(
            model_name='preview',
            name='preview_groups',
            field=models.ManyToManyField(to='pages.PreviewGroup'),
        ),
    ]
