# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-07 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20170907_1400'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SectionPreview',
            new_name='SectionPreviews',
        ),
    ]
