# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20170528_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
