# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20170517_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='url',
            new_name='link',
        ),
        migrations.AddField(
            model_name='page',
            name='link_text',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
