# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 21:55
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20170528_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectiondefault',
            name='content',
            field=tinymce.models.HTMLField(max_length=60000, null=True),
        ),
    ]
