# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20170517_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(max_length=200, upload_to='backgrounds/'),
        ),
    ]
