# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-08 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20170907_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectiontwocolumn',
            name='title_left',
        ),
        migrations.RemoveField(
            model_name='sectiontwocolumn',
            name='title_right',
        ),
    ]
