# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20170517_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationitem',
            name='type_url',
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='url',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='page',
            name='link',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
