# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20170528_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='background_color',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
