# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-08 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20170908_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionthreecolumn',
            name='title_center',
        ),
        migrations.RemoveField(
            model_name='sectionthreecolumn',
            name='title_left',
        ),
        migrations.RemoveField(
            model_name='sectionthreecolumn',
            name='title_right',
        ),
    ]
