# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20170528_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationitem',
            name='order',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
