# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-08 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20170908_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preview',
            name='preview_groups',
        ),
        migrations.AddField(
            model_name='preview',
            name='preview_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.PreviewGroup'),
        ),
        migrations.AlterField(
            model_name='preview',
            name='display_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
