# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-08 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20170908_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionpreviews',
            name='preview_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.PreviewGroup'),
        ),
    ]
