# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20170519_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationitem',
            name='display_title',
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
