# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20170604_2257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectionvideo',
            options={'verbose_name_plural': 'Sections - Single Video Template'},
        ),
        migrations.AlterModelOptions(
            name='sectionvideogroup',
            options={'verbose_name_plural': 'Sections - Video Group Template'},
        ),
    ]
