# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
        ('pages', '0010_auto_20170519_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='social',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social.Social'),
        ),
    ]
