# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20170621_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='display_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
