# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('pages', '0017_auto_20170712_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionTeam',
            fields=[
                ('content_ptr', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Content')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Team')),
            ],
            options={
                'verbose_name_plural': 'Sections - Team Template',
            },
            bases=('pages.content',),
        ),
    ]
