# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_social_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=6),
        ),
    ]
