# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_video_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_groups',
            field=models.ManyToManyField(blank=True, null=True, to='video.VideoGroup'),
        ),
    ]
