# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_auto_20170623_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='display_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='videogroup',
            name='display_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
