# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_auto_20170623_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=7),
        ),
        migrations.AddField(
            model_name='videogroup',
            name='status',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=7),
        ),
    ]
