# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_remove_video_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='entry_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='videogroup',
            name='entry_date',
            field=models.DateTimeField(null=True),
        ),
    ]
